### PR TITLE
Alarms

### PR DESCRIPTION
**Pull request by baijerry**
Finished alarm functionality. Faking JSON input, and commented actions to perform after alarm gets triggered.

### CODE REVIEW

**Comment by sunbaoshi1975** [comment]
In xlxConfig.cpp, I don't see code for reading SCT from EEPROM or writting the structure back to flash. Please leave a 'ToDo' mark at the location, if you are planning to add these snippets later.

**Comment by baijerry** [comment]
Hey Baoshi, I have made the changes. Please let me know if the current implimentation of EEPROM.get() and .put() are correct, thanks!

**Comment by sunbaoshi1975** [comment]
I have two questions:
1. Line 118 in xlxConfig.cpp "EEPROM.get(MEM_CONFIG_OFFSET, m_config);" is wrong. The object and offset should be SCT.
2. ParticleTimeSync() is a good input. We do need to do time synchronization no matter we are using Particle platform or not. So I would suggest a common timesync function. And in this function, we will execute different code snippet according to the platform.

I also want to know if you've done any unit test. In accordance with the principle of agile programming, it's important for developers to complete unit test before they submit code.

**Comment by baijerry** [comment]
Hi Baoshi,

I have fixed EEPROM and timesync, and currently am looking into unit testing frameworks. So far, I have implimented the alarms/schedule by first writing unit programs in a seperate Particle project, and moved them over once they were working. 

We will start implimenting proper unit tests once we find a suitable framework, Particle seems to have some of its own.

**Comment by uzbhutta** [comment]
Hi Baoshi,

We are experimenting with UnitTest++ (https://github.com/unittest-cpp), which seems to be popular around the Particle community, as well as GoogleTest (https://github.com/google/googletest). 

We'll write some tests and push up the repositories for your suggestions.

**Comment by sunbaoshi1975** [comment]
Please split and deliver this PR in specific topics.

**Pull request closed without merging**
