### PR TITLE
Parsing

### PR DESCRIPTION
**Pull request by uzbhutta**
Hi Baoshi,

Here is a starting point for the parsing function. It's been tested but some items are missing (denoted by TODO). I will be cleaning it up and refactoring, but I just wanted to put up this PR as a starting point to get your early input.

Thanks

### CODE REVIEW

**Comment by sunbaoshi1975** [comment]
Hi Umar,

It's wonderful to discuss your programming strategy in early stage. My comments are stated below:
1. Severe problem: You split the JSON string by '{' and '}'. But it won't work when the string contains nested JSON objects. I'll strongly suggest that we parse the incoming string as an intact JSON string rather than a concatenation of a few JSON strings. It'll work for single row situation, as well as multi-row situation if we add a 'rows = n' k-v pair.
2. Severe problem: We don't use Serial.println() for logging. Please use the log object.
3. Small problem: For the format of uid, I won't suggest we parse it as float, which is slow with regard to parsing and storage. We will parse it as a string and take the first character as the type of queue. In the case, an alphabetic letter is more user friendly.

Cheers,
Baoshi

**Comment by uzbhutta** [comment]
Hi @sunbaoshi1975. Apologies for the formatting that git picked up. The only function I modified was SmartControllerClass::CldJSONCommand. 


Here's a sample JSON that I tested with.

{\"rows\":2,
\"data\":
[
{\"op_flag\":\"PUT\",\"flash_flag\":\"UNSAVED\",\"run_flag\":\"UNEXECUTED\",\"uid\":\"2.14\",\"hour\":23,\"min\":04},
{\"op_flag\":\"POST\",\"flash_flag\":\"UNSAVED\",\"run_flag\":\"UNEXECUTED\",\"uid\":\"2.03\",\"hour\":12,\"min\":13}
]
}

**Comment by sunbaoshi1975** [comment]
There are still a few minor problems. I'll merge the PR and fix the bugs.

**Comment by sunbaoshi1975** [comment]
Sorry. The system reported conflicts, and I couldn't merge this PR. I think you may need to check and synchronize with the code that Jerry submitted, and then apply your changes on that version.

**Pull request closed without merging**
