### PR TITLE
Parsing Updated

### PR DESCRIPTION
**Pull request by uzbhutta**
Minor logic changes; converted UID into char identifier and into int id, and assigned int id variable to struct variable uid, to use for arithmetic

### CODE REVIEW

**Comment by uzbhutta** [comment]
@sunbaoshi1975 Made suggested changes

**Comment by sunbaoshi1975** [comment]
Please check these lines:
char uidChar[3];
memcpy(uidChar, &uidWhole[1], 2);
uidChar[3] = '\0';
uint8_t uidNum = atoi(uidChar);

Unexpected error will occur when the length of uidWhole is less than 3. For example, uidWhole = 'r1'.
I would write like this:
uint8_t uidNum = atoi(&uidWhole[1]);

**Comment by uzbhutta** [comment]
@sunbaoshi1975 
To account for both lengths of 2 and 3, I decided to go with the following:

```
	if (strlen(uidWhole) == 2) {
		memcpy(uidChar, &uidWhole[1], 1); //copy uidWhole starting at index 1, for length 1, into uidChar
		uidChar[2] = '\0';
	} else if (strlen(uidWhole) == 3) {
		memcpy(uidChar, &uidWhole[1], 2); //copy uidWhole starting at index 1, for length 2, into uidChar
		uidChar[3] = '\0';
	}
	uint8_t uidNum = atoi(uidChar);
```

This works for all cases of 'r5', 'r21', 'r05'.

**Comment by sunbaoshi1975** [comment]
But it doesn't work when the length is larger than 3. 
I proposed line is more adaptive and concise. I appreciate if you take my advice. :)

**Comment by uzbhutta** [comment]
My apologies. I was under the impression that atoi only converts the given index of the char to int - I didn't know it converted everything after the specified index to int.

**Pull request merged**
