### PR TITLE
Mic sensor

### PR DESCRIPTION
**Pull request by uzbhutta**
Hi Baoshi,

Sorry for the compilation errors in my PR earlier. Particle Dev has been weird for me today and seems to be creating .ino files from .cpp files. 

Anyway, here's my end-to-end implementation for the MIC. Using the IntervalTimer, it is housed within SysteTimerCB() in SmartController.ino, which calls theSys.CollectMicData(), a new function I created in xlSmartController. 

The only problem with this code I see potentially being a problem is the call UpdateJsonData() in SmartControllerClass::CollectMicData() since publishing to the cloud cannot occur as frequently as SysteTimerCB() will be cycling (25ms). Your input on how to avoid or improve this is much appreciated.

@Jerry, please review.

### CODE REVIEW

**Comment by sunbaoshi1975** [comment]
Hi Umar,

MIC is a bit complex than other sensors. I'm afraid that current code won't work properly. Did you do some unit tests? I found this project may help. You can take a look.

https://github.com/robyu/knockknock

Cheers,
Baoshi

**Comment by sunbaoshi1975** [comment]
I also searched community.particle.io. There are many threads about voice and speech. They are useful references especially to the phase II features on MIC.

**Comment by shicaoUW** [comment]
To explain Phase I vs II about MIC, in Phase I, we just want to sense the sound intensity level from the environment.  https://github.com/robyu/knockknock provides a good example. Basically, it records samples from each time window, e.g., 1000 ms (could use a parameter to set), and get the average sound intensity or power as a number. If this number is larger than a pre-set threshold, then we know there are people around. (How the threshold should be determined is a separate question.)

In Phase II, we want to test voice recognition functions. After certain trigger events (e.g., user presses certain button or did something), we will probably need to record a few seconds of voice, process it, and upload it to cloud servers for voice recognition. 

Shi

**Comment by uzbhutta** [comment]
Hi Baoshi and Shi,

The current code is simply reading in voltage values output by the mic. I tested the code in a sample program - as sound level increased, the voltage value output was higher. 

Thanks for the suggestions and links. I will take a look and have another go at a more useful implementation. 

Cheers,
Umar

**Comment by shicaoUW** [comment]
The problem with instance the voltage value is that it may jump up and down from time to time, subject to noise and sudden and short peak sound like a motor cycle running pass the house.  Taking the average from some time window is then smoother and better for knowing general environmental noise level.

**Pull request closed without merging**
