### PR TITLE
Alarms

### PR DESCRIPTION
**Pull request by baijerry**
Hi BaoShi,

I planed out the schedule/alarm feature on paper, and have started to impliment it. Please let me know if there are any problems with my setup so far. 

I have defined the SCT structure in xlxConfig.h, and a few helper function declarations (with a more to come). 

My biggest question is in regards to the bitfields. I have calculated that my current implimentation uses 22 bytes per row, which means the max # of rows in the SCT is 11. Looking at your code, the bitfields of the structs defined in xlxConfig.h seem to be in bits not bytes. Is this right? For example, line 43 in xlxConfig.h says that the number of devices can be represented with 1 bit. This seems wrong, should we multiply every bitfield previously defined by 8? 

Thanks,
Jerry

### CODE REVIEW

**Comment by sunbaoshi1975** [comment]
You are correct. There shouldn't be bit fields in all structures. We can simply remove them. Thanks.

**Comment by sunbaoshi1975** [comment]
Just reviewed the changes you made. You did very well. I'd like to give some comment.
1. It's not proper to put MAX_SCT_ENTRY in xliCommon.h. A better place should be xlxConfig.h. Alternatively, I think we can use (int)(256 / sizeof(SCT)) instead of constant.
2. Regarding to SCT structure, I'd suggest to include an action id or scenario id, instead of device type structure. Once a schedule is triggered, it'll perform a corresponding action or switch to the specific scenario. In this case, an action is more general. It could be anything, including change scenario, sending notification, etc.
3. Since some code snippets are not completed, I wouldn't merge this PR for now.
Look forward to discussing with you.

**Comment by baijerry** [comment]
Hi BaoShi,
Thank you for your feedback, I have a followup question:
What did you mean by "instead of device type structure"? Are you refering to DevStatus_t (device status struct) or UC type (device type variable)? I used DevStatus_t because it contained the color data for each ring, should I expand this out and just include the Hue_t color structs individually in my Schedule Table structure? 
Thanks,
Jerry BaiStudent, Systems Design EngineeringUniversity of WaterlooWaterloo, ON, Canada
Student ID: 20561350Waterloo Email: jerry.bai@uwaterloo.ca

Date: Tue, 17 May 2016 20:03:46 -0700

**Comment by sunbaoshi1975** [comment]
Hi Jerry,

I referred to DevStatus_t. I think it’ll be better if we use an id of a structure or an object. That object can also be referred by other SCT. There won’t be duplicated data.

Cheers,
Baoshi

**Comment by baijerry** [comment]
Hi Baoshi, 

From my understanding, would the stucture replacing DevStatus_t include the 3 Hue_t structs, the device id, as well as the action id?

**Pull request closed without merging**
